version: '3.3'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  keycloak:
    image: mihaibob/keycloak:15.0.1
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
